# Generated by Django 4.2.5 on 2023-09-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_delete_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='none.png', upload_to='media/'),
        ),
    ]
