# Generated by Django 4.2.5 on 2023-09-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
