# Generated by Django 4.2.5 on 2023-09-11 16:22

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(validators=[main.models.validate_amount]),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(validators=[main.models.validate_price]),
        ),
    ]
