# Generated by Django 4.2.5 on 2023-09-15 10:29

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_item_amount_alter_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.FloatField(default=0.0, validators=[main.models.validate_rating]),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=1, validators=[main.models.validate_amount]),
        ),
    ]
