# Generated by Django 4.2.5 on 2023-10-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='static\\images\\Vault.png', upload_to='albums/'),
        ),
    ]
