# Generated by Django 4.2.5 on 2023-10-02 13:56

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=1, validators=[main.models.validate_amount]),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.FloatField(default=0.0, validators=[main.models.validate_rating]),
        ),
    ]
